#!/usr/bin/env bash


verifyBase() {
  # test if variable is defined and non-null
  [[ ! "${#1}" -gt 0 ]] && \
    notify '_BASE variable cannot be zero length!' && \
    exit 1

  # test is relative or absolute
  if [[ "${1}" = /* ]];then
    :
  else
    _BASE="/${_CWD}/${_BASE}"
  fi


  # test if directory exists
  if [[ ! -d "${1}" ]]; then
    notify '_BASE path must exist!'
    exit 1
  fi
  # test if directory is writeable
  if [[ ! -w "${1}" ]]; then
    notify '_BASE path must be writable!'
    exit 77
  fi

  return 0
}
